name: Prison
version: '${project.version}'
main: org.latuk.prison.Prison
api-version: '1.16'
commands:
  shop:
    description: shop command
  sell:
    description: sell items command
  mines:
    description: mines command
  lvl:
    description: level command
    aliases:
      - level
      - lvlup
      - levelup
      - дмд
      - дмдгз
      - думудгз
  menu:
    description: menu command